
name: "Build on UNIX"
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [{tripple: x64-linux, on: ubuntu-24.04}, {tripple: arm64-osx, on: macos-26}]

    name: ${{matrix.os.tripple}}
    runs-on: ${{matrix.os.on}}

    env:
      DEBUG_BUILD_DIR: ${{github.workspace}}/out/build/${{matrix.os.tripple}}/Debug
      RELEASE_BUILD_DIR: ${{github.workspace}}/out/build/${{matrix.os.tripple}}/Release
      INSTALL_DIR: ${{github.workspace}}/out/install
      VCPKG_ROOT: ${{github.workspace}}/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg/binary-sources
      VCPKG_BINARY_SOURCES: clear;file,${{github.workspace}}/vcpkg/binary-sources,readwrite
      VCPKG_FEATURE_FLAGS: binarycaching

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install development environment (Ubuntu)
        if: matrix.os.on == 'ubuntu-24.04'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod 755 llvm.sh
          echo "" | sudo ./llvm.sh 20
          sudo apt-get install -y perl autoconf-archive ninja-build cmake pkg-config clang-20 lldb-20 lld-20 clangd-20
          sudo ln -f /usr/bin/clang-20 /usr/bin/clang
          sudo ln -f /usr/bin/clang++-20 /usr/bin/clang++

      - name: Install development environment (MacOS)
        if: matrix.os.on == 'macos-26'
        run: |
          brew install automake autoconf autoconf-archive

      - name: Create vcpkg cache dir
        run: mkdir ${{env.VCPKG_DEFAULT_BINARY_CACHE}}

      - name: Get vcpkg commit id
        working-directory: vcpkg
        run: git rev-parse HEAD >commit.txt

      - name: Install vcpkg
        working-directory: vcpkg
        run: ./bootstrap-vcpkg.sh

      - name: Restore vcpkg binary-cache
        id: restore-vcpkg-cache
        uses: actions/cache/restore@v4
        with:
          path: vcpkg/binary-sources/**/*.zip
          key: vcpkg-cache-${{matrix.os.tripple}}-${{hashFiles('vcpkg.json', 'vcpkg/commit.txt')}}-1

      # MacOS installation has a bug where it doesn't set CMAKE_MAKE_PROGRAM
      # even though CMake does find ninja during startup.
      - name: CMake - Configure (MacOS)
        if: matrix.os.on == 'macos-26'
        run: cmake -D "CMAKE_MAKE_PROGRAM=/opt/homebrew/bin/ninja" --preset=${{matrix.os.tripple}} .

      - name: CMake - Configure
        if: matrix.os.on != 'macos-26'
        run: cmake --preset=${{matrix.os.tripple}} .

      - name: Save vcpkg binary-cache
        uses: actions/cache/save@v4
        id: save-vcpkg-cache
        if: always() && steps.restore-vcpkg-cache.outputs.cache-hit != 'true'
        with:
          path: vcpkg/binary-sources/**/*.zip
          key: ${{steps.restore-vcpkg-cache.outputs.cache-primary-key}}

      - name: CMake - Build (Debug)
        run: cmake --build --preset=${{matrix.os.tripple}}-dbg --parallel 1 .

      - name: CMake - Build (Release)
        run: cmake --build --preset=${{matrix.os.tripple}}-rel --parallel 1 .

      - name: Run tests (Debug)
        working-directory: ${{env.DEBUG_BUILD_DIR}}
        run: ./hktests-dbg --gtest_output=xml:hktests-dbg.xml

      - name: Run tests (Release)
        working-directory: ${{env.RELEASE_BUILD_DIR}}
        run: ./hktests-rel --gtest_output=xml:hktests-rel.xml
    
